GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOjE0LCJpYXQiOjE3MzE0OTE5MTIsImV4cCI6MTczMTQ5MTk0MiwiaXNzIjoibXkgYXBpLmNvbSJ9.BdqWQ80hssVfiEkeCXpW9WLdd1gtZBtGBF7ClSlffzg

###Login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "kalitopic7@mail.com",
    "password":"12345678"
} 


###Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "kalitopic7@mail.com",
    "password":"12345678"
} 

###Refresh-token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOjE0LCJpYXQiOjE3MzE0ODc1NzQsImV4cCI6MTc2MzA0NTE3NCwiaXNzIjoibXkgYXBpLmNvbSJ9.u2_sqn4iW86PFIPtKj6aapxoyRa6wcdNdPPNqJqdFBU"

}

###Logout route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOjE0LCJpYXQiOjE3MzE0ODk3NDUsImV4cCI6MTc2MzA0NzM0NSwiaXNzIjoibXkgYXBpLmNvbSJ9.mo9VDW0XVs_bWncchnbP6yhU5A-YIQHBsVyV20MiE3c"    
}
