GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOjE0LCJpYXQiOjE3MzE0MTQ2MDQsImV4cCI6MTczMTQxODIwNCwiaXNzIjoibXkgYXBpLmNvbSJ9.pLv_dW1bR7V_bM9L_uWVWMx4LM69iyt3pOdebJLy-2o

###Login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "kalitopic7@mail.com",
    "password":"12345678"
} 


###Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "kalitopic7@mail.com",
    "password":"12345678"
} 

###Refresh-token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOjE0LCJpYXQiOjE3MzE0MTQzMzIsImV4cCI6MTc2Mjk3MTkzMiwiaXNzIjoibXkgYXBpLmNvbSJ9.DzQuw1FykVhccAKX9hzP3KGWsc8ipZSWEovT4b1e4JE"

}

###Logout route
DELETE http://localhost:3000/auth/logout
