GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOjEzLCJpYXQiOjE3MzEzOTk5NDIsImV4cCI6MTczMTM5OTk1NywiaXNzIjoibXkgYXBpLmNvbSJ9.HPh53q4PLmDv_CteMUZDoRWdlQn1F0LdJMDCK_Jmq6c

###Login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "kalitopic7@mail.com",
    "password":"12345678"
} 


###Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "kalitopic7@mail.com",
    "password":"12345678"
} 

###Refresh-token route
POST http://localhost:3000/auth/refresh-token


###Logout route
DELETE http://localhost:3000/auth/logout
